-- +goose Up
-- +goose StatementBegin

-- Phase 26: Protect historical order hierarchy.
--
-- orders.manager_id, team_lead_id, manager_team_id, team_lead_team_id were
-- created with ON DELETE SET NULL, meaning hard-deleting a user or team would
-- silently wipe the hierarchy snapshot out of every historical order and make
-- income reports unauditable.
--
-- Required behaviour:
--   • Columns remain NULLABLE — orders created without a full hierarchy
--     (e.g. seller has no manager) legitimately have NULL here.
--   • When a value IS set, the referenced user/team MUST NOT be hard-deleted.
--     ON DELETE RESTRICT enforces this at the DB level, regardless of which
--     application path (or raw SQL) triggers the deletion.
--
-- Current state:
--   Both users and teams use soft-delete only (set deleted_at).
--   This migration adds a DB-level safety net for future protection.
--
-- FK names auto-generated by PostgreSQL from inline REFERENCES in 00023:
--   orders_manager_id_fkey       → users(id)
--   orders_team_lead_id_fkey     → users(id)
--   orders_manager_team_id_fkey  → teams(id)
--   orders_team_lead_team_id_fkey → teams(id)

-- ── manager_id ────────────────────────────────────────────────────────────────
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_manager_id_fkey;
ALTER TABLE orders
    ADD CONSTRAINT orders_manager_id_fkey
    FOREIGN KEY (manager_id)
    REFERENCES users (id)
    ON DELETE RESTRICT;

-- ── team_lead_id ──────────────────────────────────────────────────────────────
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_team_lead_id_fkey;
ALTER TABLE orders
    ADD CONSTRAINT orders_team_lead_id_fkey
    FOREIGN KEY (team_lead_id)
    REFERENCES users (id)
    ON DELETE RESTRICT;

-- ── manager_team_id ───────────────────────────────────────────────────────────
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_manager_team_id_fkey;
ALTER TABLE orders
    ADD CONSTRAINT orders_manager_team_id_fkey
    FOREIGN KEY (manager_team_id)
    REFERENCES teams (id)
    ON DELETE RESTRICT;

-- ── team_lead_team_id ─────────────────────────────────────────────────────────
ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_team_lead_team_id_fkey;
ALTER TABLE orders
    ADD CONSTRAINT orders_team_lead_team_id_fkey
    FOREIGN KEY (team_lead_team_id)
    REFERENCES teams (id)
    ON DELETE RESTRICT;

-- +goose StatementEnd

-- +goose Down
-- +goose StatementBegin

-- Reverse: restore ON DELETE SET NULL (reverts to pre-Phase-26 state).

ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_manager_id_fkey;
ALTER TABLE orders
    ADD CONSTRAINT orders_manager_id_fkey
    FOREIGN KEY (manager_id)
    REFERENCES users (id)
    ON DELETE SET NULL;

ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_team_lead_id_fkey;
ALTER TABLE orders
    ADD CONSTRAINT orders_team_lead_id_fkey
    FOREIGN KEY (team_lead_id)
    REFERENCES users (id)
    ON DELETE SET NULL;

ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_manager_team_id_fkey;
ALTER TABLE orders
    ADD CONSTRAINT orders_manager_team_id_fkey
    FOREIGN KEY (manager_team_id)
    REFERENCES teams (id)
    ON DELETE SET NULL;

ALTER TABLE orders DROP CONSTRAINT IF EXISTS orders_team_lead_team_id_fkey;
ALTER TABLE orders
    ADD CONSTRAINT orders_team_lead_team_id_fkey
    FOREIGN KEY (team_lead_team_id)
    REFERENCES teams (id)
    ON DELETE SET NULL;

-- +goose StatementEnd
